### ISSUE TITLE
Add prometheus-operator ServiceMonitor

### ISSUE THREAD

**Issue by galindro** [openebs/charts#149]
Would be really nice to have it. Details here: https://coreos.com/blog/the-prometheus-operator.html

**Comment by si458** [comment]
@galindro it already partly exists
https://github.com/openebs/openebs/tree/master/k8s#optional-enable-monitoring-using-prometheus-operator
https://github.com/openebs/openebs/blob/master/k8s/openebs-servicemonitor.yaml

**Comment by kmova** [comment]
@galindro @si458 - we are pushing the monitoring related configurations into https://github.com/openebs/monitoring

Would love to get your feedback on this new feature and see how to improve it further.

**Comment by galindroasml** [comment]
Hi @kmova, unfortunately I'm not working on this project anymore.

**Comment by galindro** [comment]
Hi @kmova. Unfortunately, I'm not working on it anymore since last year's end.
