### ISSUE TITLE
matchLabels for charts are wrong

### ISSUE THREAD

**Issue by si458** [openebs/charts#160]
Hi,
it seems the most of the matchLabels are incorrect?
take `openebs-snapshot-operator` it focuses on 
```
matchLabels:
  app: openebs
  release: openebs
```
but this targets all pods instead of just the snapshot pods

however if you look at the [direct yaml deployment version](https://github.com/openebs/charts/blob/gh-pages/openebs-operator.yaml), the matchLabels show
```
matchLabels:
  name: openebs-snapshot-operator
  openebs.io/component-name: openebs-snapshot-operator
```
which is correct and targets only the required pods!

**Comment by si458** [comment]
im guessing this was missed with the release of the 2.3.0?
if you deploy the chart, its still listing all pods in each deployment, unlike the yaml file directly

**Comment by prateekpandey14** [comment]
@si458 , looks like from the k8s 1.16 onwards in `apps.v1` [Deployment's label selector is immutable after it gets created]( https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates).

Even i have tried to change the label selector and got the error 
```
$ helm upgrade openebs -n openebs .
cannot patch "openebs-snapshot-operator" with kind Deployment: Deployment.apps "openebs-snapshot-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"openebs", "component":"snapshot-operator", "release":"openebs"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable 
```

**Comment by si458** [comment]
@prateekpandey14 that's a bummer... it would have fixed new installs but not existing installs groan :(
