### ISSUE TITLE
images for node disk manager are wrong

### ISSUE THREAD

**Issue by ErroKokkarda** [openebs/charts#161]
Hello,

helm chart tries to reference node-disk-manager:v0.9.0 but one gets report that it is unauthorized
if one changes image to node-disk-manager-amd64 it gets pulled

**Comment by akhilerm** [comment]
@ErroKokkarda Did you use the latest charts.? Because the default image tag points to `0.9.0`

Also , it is recommended to use the `openebs/node-disk-manager:0.9.0`,  (without the `v` prefix). Because this is a multiarch image and going forward we will be building and pushing multiarch images only.

**Comment by ErroKokkarda** [comment]
I used this on rancher and helm charts once checking them out it seems try to pull from quay.io/openebs/node-disk-manager
for 2.x version of openebs
once deploying 1.x openebs worked

your suggestion does work openebs/node-disk-manager:0.9.0 is an image I can pull from local
but not quay.io/openebs/node-disk-manager:0.9.0

thanks. I'm happy with that answer and I might check from where does rancher pull these helm charts and image be parametrized

we can close this if you want if you guys don't supply charts for them so quay.io/openebs/node-disk-manager is referenced from here somewhere and then it is not pullable

**Comment by akhilerm** [comment]
We are not pushing multiarch images to quay as quay did not support multiarch images at the time. 

Also because of the frequent outages we moved our default registry from quay to docker hub.

> I might check from where does rancher pull these helm charts and image be parametrized

thanks. Can you update that in the issue once you get the information, so that we can fix it in the charts.

**Comment by ErroKokkarda** [comment]
I think they come from here 
https://github.com/rancher/charts/blob/master/charts/openebs/v2.1.0/questions.yml
they maintain their library charts from here I guess but their interface might but defaults that reference quay

**Comment by akhilerm** [comment]
@prateekpandey14 , PTAL on [this](https://github.com/rancher/charts/blob/master/charts/openebs/v2.1.0/questions.yml.). I think we should update the default in the questions section to docker hub instead of quay. 

The charts are not using quay, but from the options the images are taken from quay.

**Comment by prateekpandey14** [comment]
@ErroKokkarda @akhilerm sure i will take a look and update the images repository.

**Comment by prateekpandey14** [comment]
@ErroKokkarda PR https://github.com/rancher/charts/pull/825 has been raised to fix the image. thanks for creating an issue.

**Comment by prateekpandey14** [comment]
Closing this issue , the PR rancher/charts#854 is merged and fix will available in openebs 2.2.0 release.
