### ISSUE TITLE
What does admission-server do?

### ISSUE THREAD

**Issue by alexppg** [openebs/charts#165]
Hi
Not sure if this is the right place, but I'll try it anyway. What I loose if I deactivate the admission server? I understand what an admission controller does generally, which is "validate" k8s objects. But I can't find information about what exactly does **this** admission controller on the documentation.
Thanks for your time.
PD: The chart and openebs are very cool projects, thanks !

**Comment by prateekpandey14** [comment]
@alexppg openebs admission controller basically validates the following operations
- PVC delete operations for cstor volumes to validate source PVC can't be deleted if cloned PVC exists
- Validates that the cloned PVC size is same as source PVC size
- Openebs namespace validation if openebs pool/volume exists
