### ISSUE TITLE
mayastor support

### ISSUE THREAD

**Issue by AntonOfTheWoods** [openebs/charts#168]
Parts of the docs suggest `mayastor` should now be considered beta, and for new-comers wishing to try it out with all the integrated features that the helm chart brings, not having helm support for `mayastor` adds significant challenges. Is there a timeline for introducing `mayastor` support, or is the reply just "when it's GA"?

**Comment by kmova** [comment]
@AntonOfTheWoods - we are currently refactoring the way helm charts are setup to be more modular and to keep it in sync with the individual data engine projects. In this release (dec 15th), we have spent time in adding charts for cstor, local pv, zfs local pv. 

The next release (due jan 15th), we will focus on mayastor charts.

**Comment by kmova** [comment]
cc: @GlennBullingham @bobek

**Comment by bobek** [comment]
Incidentally we are just about to do revamp of the toolchain for Mayastor at https://github.com/openebs/Mayastor/issues/569

**Comment by AntonOfTheWoods** [comment]
This all looks very promising, thanks for the great work!

**Comment by bobek** [comment]
BTW the initial version of the helm chart is available at https://github.com/openebs/Mayastor/tree/develop/chart

**Comment by AntonOfTheWoods** [comment]
Though it adds a bit of extra complexity, I have been using Bitnami's [common library chart](https://github.com/bitnami/charts/tree/master/bitnami/common) for my charts recently, and found using their template to be a great starter along with the common. You might hate it of course...

**Comment by Davincible** [comment]
So how is this going?
