### ISSUE TITLE
Helm Chart support for imagePullSecrets to counter Dockerhub Rate Limiting

### ISSUE THREAD

**Issue by Atharex** [openebs/charts#172]
Would be great if the helm chart enabled us to specify registry credentials, so we could avoid the Dockerhub's rate-limitations for free accounts!

**Comment by kmova** [comment]
Available in 2.4.0 via the PR: https://github.com/openebs/charts/pull/174

**Comment by Atharex** [comment]
Awesome! Thanks for for solving this 👍
