### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by maxisam** [openebs/charts#205]
Is there a way to do this with the chart?

https://docs.openebs.io/docs/next/uglocalpv-hostpath.html#create-storageclass

It would be nice to customize the storageclass

at least a way to add NodeAffinityLabel

**Comment by akhilerm** [comment]
It's already available here. It's the helm chart for dynamic localPV https://openebs.github.io/dynamic-localpv-provisioner/

**Comment by maxisam** [comment]
so is that the chart for localpv only? If I just need localpv, I should just use that chart?

Thanks!

**Comment by akhilerm** [comment]
> so is that the chart for localpv only? If I just need localpv, I should just use that chart?
> 
> Thanks!

@maxisam Yes.

**Comment by maxisam** [comment]
Thank you!
