### ISSUE TITLE
Where can I find it https://openebs.github.io/charts/openebs-operator-1.6.0.yaml

### ISSUE THREAD

**Issue by looking-for-my-magic-bean** [openebs/charts#292]
This configuration file was previously applied in one side of the application, but it was found to be invalid recently. Where can I find it again?

**Comment by Ab-hishek** [comment]
Hi @looking-for-my-magic-bean. OpenEBS charts version 1.6.0 are no longer supported and will be removed in the upcoming releases. You can find them inside the deprecated folder: https://github.com/openebs/charts/blob/gh-pages/deprecated/openebs-operator-1.6.0.yaml
